# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83db4d0692ac69790f390924431b52baf42ad5527c0d42e482f861f23da45984d97309f76316ddfbd7d34b4a7631ee1385d37681c8ff40aea30f12dad8556f40

test:
  secret_key_base: bc6af04f0771c38d2bbba2adb501148e3ecf78a90372dc3e722c1e6dbeed3efd63a41f20fcfb30a6ac936a33f3a8716baabf14df44c9a411448e2022d7e29e25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
